// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies.Services.MovieAPI.Data;

#nullable disable

namespace Movies.Services.MovieAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240807093004_addMovieAndSeedTable")]
    partial class addMovieAndSeedTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Movies.Services.MovieAPI.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Description = "A thief who enters the dreams of others to steal secrets from their subconscious.",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Inception",
                            Price = 5.0,
                            category = "Sci-Fi"
                        },
                        new
                        {
                            MovieId = 2,
                            Description = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "The Shawshank Redemption",
                            Price = 7.0,
                            category = "Drama"
                        },
                        new
                        {
                            MovieId = 4,
                            Description = "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Pulp Fiction",
                            Price = 6.0,
                            category = "Crime"
                        },
                        new
                        {
                            MovieId = 5,
                            Description = "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Forrest Gump",
                            Price = 4.0,
                            category = "Drama"
                        },
                        new
                        {
                            MovieId = 6,
                            Description = "A computer programmer discovers a dystopian world inside a simulation and joins a rebellion to overthrow the machines that control it.",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "The Matrix",
                            Price = 10.5,
                            category = "Sci-Fi"
                        },
                        new
                        {
                            MovieId = 7,
                            Description = "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Schindler's List",
                            Price = 2.5,
                            category = "Drama"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
